# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np
arr=np.random.randint(1,10,size=(5,5))
print(arr)
arr[2:3]=1
print(arr)

[[4 1 5 4 1]
 [5 8 2 8 3]
 [9 9 2 3 3]
 [8 2 9 1 5]
 [8 9 6 2 2]]
[[4 1 5 4 1]
 [5 8 2 8 3]
 [1 1 1 1 1]
 [8 2 9 1 5]
 [8 9 6 2 2]]


 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagon

In [ ]:
arr=np.random.randint(1,16,size=(4,4))
print(arr)
b=np.array([[0],[1],[2],[3]])
arr[b,b]=0
print(arr)

[[15  7  5  4]
 [ 7 14  6 13]
 [11  3  3  9]
 [ 9 11  7  1]]
[[ 0  7  5  4]
 [ 7  0  6 13]
 [11  3  0  9]
 [ 9 11  7  0]]



### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [15]:
arr=np.random.randint(1,36,size=(6,6))
print(arr)
arr[3:6,2:5]

[[25 11 30 29 25 12]
 [20 30  5 19 29 29]
 [ 9 11 19 34 14  1]
 [11 34 29 28  9  4]
 [26 19 21 11 31 23]
 [ 9 22  2  4  4 17]]


array([[29, 28,  9],
       [21, 11, 31],
       [ 2,  4,  4]])

In [22]:
arr=np.random.randint(100,size=(5,5))
print(arr)
arr[::4,::4]

[[19 93 33 32 82]
 [76  4 95 27 84]
 [47 93 64 83 67]
 [38 40 68 56 98]
 [45 57 12 44 99]]


array([[19, 82],
       [45, 99]])

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [13]:
import numpy as np 
import random
arr=np.random.randint(1,36,size=(3,4))
arr1=np.random.randint(1,36,size=(3,4))
print(arr+arr1)
print(arr-arr1)
print(arr*arr1)
print(arr/arr1)

[[39 40 16 20]
 [29 35 33 37]
 [36 31 44 12]]
[[ 27 -26 -12  -2]
 [  3  -3 -25  19]
 [-32   9  12  -2]]
[[198 231  28  99]
 [208 304 116 252]
 [ 68 220 448  35]]
[[5.5        0.21212121 0.14285714 0.81818182]
 [1.23076923 0.84210526 0.13793103 3.11111111]
 [0.05882353 1.81818182 1.75       0.71428571]]


In [39]:
arr=np.random.randint(1,16,size=(4,4))
print(arr)
print("\n Column sum")
print(arr.sum(axis=0))
print("\n Row sum")
print(arr.sum(axis=1))

[[ 2  2  7  2]
 [10  6  3 12]
 [12  8 13  5]
 [ 5 14  3 15]]

 Column sum
[29 30 26 34]

 Row sum
[13 31 38 37]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [49]:
arr = np.random.randint(1,11,size=(5,5))
print(arr)
print("mean ==>",arr.mean())
print("median ==>",np.median(arr))
print("Standard deviation ==>",np.std(arr))
print("Variance ==>",np.var(arr))

[[ 5 10  5  4  6]
 [ 8  7  3  1  5]
 [ 2  6  3 10  7]
 [ 9  6  4  5  4]
 [ 3  4  9  8  3]]
mean ==> 5.48
median ==> 5.0
Standard deviation ==> 2.45144855136713
Variance ==> 6.009599999999999


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [12]:
arr=np.random.randint(1,11,size=(3,3))
arr1=np.random.randint(1,11,size=(3,1))
print(arr)
print(arr1)
print(arr1+arr)

[[ 5  5  7]
 [10 10  2]
 [ 8  4 10]]
[[7]
 [1]
 [8]]
[[12 12 14]
 [11 11  3]
 [16 12 18]]
