In [29]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9])
for i in arr:
    if(i%2==0):
        print(i)

arr.shape
arr[1:4:2]
arr.reshape(3,3)



2
4
6
8


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=arr1.reshape(3,2)
# 3d array
print(arr2)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
print(a[0][1])

2


In [14]:
import numpy as np 
a1=np.random.randint(1,10,size=(2,3))
print(a1)
print(a)
print(a1-a)

[[1 1 9]
 [9 6 9]]
[[1 2 3]
 [4 5 6]]
[[ 0 -1  6]
 [ 5  1  3]]


In [ ]:
a2=10*(np.random.randint(10,100,size=(2,3)))
a3=np.array([4])
print(a2)
np.sqrt(a2)

np.random.randint(1,10,size=(2,3))

[[900 890 110]
 [550 300 240]]


array([[30.        , 29.83286778, 10.48808848],
       [23.4520788 , 17.32050808, 15.49193338]])

In [26]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[1:])
print(arr[1:,2:])
print(arr[0:][2:])
print(arr[0::2,1::2])

[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[[ 9 10 11 12]]
[[ 2  4]
 [10 12]]
